### ISSUE TITLE
Composer file still says justintadlock/hybrid-core instead of justintadlock/hybrid-contracts

### ISSUE THREAD

**Issue by skyshab** [themehybrid/hybrid-contracts#1]
The composer file still says justintadlock/hybrid-core instead of justintadlock/hybrid-contracts, making it not able to be installed.

**Comment by saas786** [comment]
Fixed in: https://github.com/themehybrid/hybrid-contracts/commit/b379b03e09afb81225598de0f1626b816eab70b0#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L2
